# Mokey goreleaser configs
# See here: https://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    ldflags:
      - -s -w -X github.com/ubccr/mokey/server.Version={{.Version}}
      - -extldflags=-static
    tags:
      - sqlite_omit_load_extension
      - osusergo
      - netgo
archives:
  - id: release
    wrap_in_directory: true
    name_template: >-
      {{- .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - NOTICE
      - README.md
      - ChangeLog.md
      - mokey.toml.sample
nfpms:
  - vendor: University at Buffalo
    homepage: https://github.com/ubccr/mokey
    maintainer: Andrew E. Bruno <aebruno2@buffalo.edu>
    license: MIT
    description: |-
      FreeIPA self-service account management tool
    formats:
      - deb
      - rpm
    overrides:
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
        scripts:
          postinstall: ./scripts/nfpm/postinstall.sh
      rpm:
        file_name_template: >-
          {{- .ProjectName }}-
          {{- .Version }}-
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "arm64" }}aarch64
          {{- else }}{{ .Arch }}{{ end }}
        scripts:
          postinstall: ./scripts/nfpm/postinstall.sh
    rpm:
      signature:
        key_file: key.gpg
    deb:
      signature:
        key_file: key.gpg
    contents:
      - src: ./scripts/nfpm/mokey.toml.default
        dst: /etc/mokey/mokey.toml
        type: "config|noreplace"
      - src: ./scripts/nfpm/mokey.env
        dst: /etc/default/mokey
        type: "config|noreplace"
      - src: ./scripts/nfpm/mokey.service
        dst: /usr/lib/systemd/system/mokey.service
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: desc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - '^docs:'
      - 'typo'
